services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      # This line makes Autumn available at port 5006 of the device you run the server on,
      # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
      - '5006:5006'
    environment:
      # Uncomment any of the lines below to set configuration options.
      # - AUTUMN_HTTPS_KEY=/data/selfhost.key
      # - AUTUMN_HTTPS_CERT=/data/selfhost.crt
      # - AUTUMN_PORT=5006
      # - AUTUMN_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - AUTUMN_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - AUTUMN_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      # Change './actual-data' below to the path to the folder you want Autumn to store its data in on your server.
      # '/data' is the path Autumn will look for its files in by default, so leave that as-is.
      - ./actual-data:/data
    restart: unless-stopped
